apiVersion: v2
name: zeep-vane
description: Self-hosted status page and uptime dashboard, powered by your own Datadog SLOs
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - status-page
  - uptime
  - datadog
  - observability
  - self-hosted
home: https://github.com/zeeplabs/zeep-vane
sources:
  - https://github.com/zeeplabs/zeep-vane
maintainers:
  - name: zeeplabs
    url: https://github.com/zeeplabs
