apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeep-vane.fullname" . }}
  labels:
    {{- include "zeep-vane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "zeep-vane.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
