//go:build integration

package db

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/zeeplabs/zeep-vane/internal/dbtest"
)

// TestSessionsMigration_AppliesClean_AndFKCascade proves that
// 0031_sessions.up.sql applies cleanly on top of the previous migrations
// (it depends on the `users` table from 0024), the table and its two
// indexes are created with the expected shapes, the FK rejects orphan
// inserts, and ON DELETE CASCADE actually fires when the referenced user
// is deleted - so admins.go:631-637 deleting a `users` row when its
// last membership is removed will not leave sessions rows orphaned.
//
// Uses a fresh scratch database (newScratchDatabase) so the test is
// self-contained - no dependence on whatever state other tests in this
// package left behind in the shared TEST_DATABASE_URL.
func TestSessionsMigration_AppliesClean_AndFKCascade(t *testing.T) {
	dsn := newScratchDatabase(t)

	if err := MigrateUp(dsn, "migrations"); err != nil {
		t.Fatalf("MigrateUp() returned unexpected error: %v", err)
	}

	ctx := context.Background()
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatalf("pgxpool.New() returned unexpected error: %v", err)
	}
	t.Cleanup(pool.Close)

	// Table exists with the expected columns and types.
	expectedColumns := map[string]string{
		"id":           "uuid",
		"user_id":      "uuid",
		"user_agent":   "text",
		"ip":           "text",
		"created_at":   "timestamp with time zone",
		"last_seen_at": "timestamp with time zone",
		"revoked_at":   "timestamp with time zone",
	}
	rows, err := pool.Query(ctx, `
		SELECT column_name, data_type
		FROM information_schema.columns
		WHERE table_schema = 'public' AND table_name = 'sessions'
	`)
	if err != nil {
		t.Fatalf("querying information_schema.columns returned unexpected error: %v", err)
	}
	gotColumns := map[string]string{}
	for rows.Next() {
		var name, dtype string
		if err := rows.Scan(&name, &dtype); err != nil {
			t.Fatalf("scanning column row returned unexpected error: %v", err)
		}
		gotColumns[name] = dtype
	}
	rows.Close()
	for name, dtype := range expectedColumns {
		if got := gotColumns[name]; got != dtype {
			t.Errorf("sessions.%s type = %q, want %q", name, got, dtype)
		}
	}

	// Both indexes exist.
	for _, want := range []string{
		"sessions_user_id_created_at_idx",
		"sessions_user_id_active_idx",
	} {
		var exists bool
		if err := pool.QueryRow(ctx,
			`SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'sessions' AND indexname = $1)`,
			want,
		).Scan(&exists); err != nil {
			t.Fatalf("querying pg_indexes for %s returned unexpected error: %v", want, err)
		}
		if !exists {
			t.Errorf("index %s does not exist", want)
		}
	}

	// gen_random_uuid() is enabled (PG 13+ core; no extension dependency)
	// and the DEFAULT on `id` is wired so INSERT can omit it. Insert a
	// fixture user (users table is from 0024_multi_tenancy_core) and a
	// session for that user, both via tenant-scoped INSERT to satisfy
	// users.email_verified_at default and FK target existence.
	dbtest.LockUsersTable(t, ctx, dsn)
	email := uniqueTestEmail(t)
	t.Cleanup(func() {
		_, _ = pool.Exec(ctx, "DELETE FROM users WHERE email = $1", email)
	})

	var userID, sessionID string
	if err := pool.QueryRow(ctx,
		"INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id",
		email, "hash-sessions-migration-test",
	).Scan(&userID); err != nil {
		t.Fatalf("insert fixture user returned unexpected error: %v", err)
	}
	if err := pool.QueryRow(ctx,
		"INSERT INTO sessions (user_id) VALUES ($1) RETURNING id",
		userID,
	).Scan(&sessionID); err != nil {
		t.Fatalf("insert session (id generated by DEFAULT) returned unexpected error: %v", err)
	}
	if sessionID == "" {
		t.Error("session id is empty after INSERT with DEFAULT, want gen_random_uuid() to populate it")
	}

	// Orphan insert (user_id pointing at a UUID nobody owns) must be
	// rejected by the foreign key - proves the FK is actually present,
	// not just declared in SQL we never tested.
	if _, err = pool.Exec(ctx,
		"INSERT INTO sessions (user_id) VALUES (gen_random_uuid())"); err == nil {
		t.Fatal("insert with nonexistent user_id returned nil error, want foreign key violation")
	}

	// CASCADE: deleting the user deletes the session in the same
	// statement - one DELETE, no separate session cleanup needed.
	if _, err := pool.Exec(ctx, "DELETE FROM users WHERE id = $1", userID); err != nil {
		t.Fatalf("DELETE FROM users returned unexpected error: %v", err)
	}

	var sessionCount int
	if err := pool.QueryRow(ctx,
		"SELECT COUNT(*) FROM sessions WHERE id = $1",
		sessionID,
	).Scan(&sessionCount); err != nil {
		t.Fatalf("counting remaining sessions after user delete returned unexpected error: %v", err)
	}
	if sessionCount != 0 {
		t.Errorf("sessions for deleted user = %d, want 0 (ON DELETE CASCADE should have removed the row)", sessionCount)
	}
}
